language: go
os: linux
dist: trusty
sudo: required
before_install:
  - sudo apt-get install socat wget
  - wget -O ~/diagslave.linux.i386 'https://raw.githubusercontent.com/xft/modbus/master/test/tools/diagslave.linux.i386'
  - chmod a+x ~/diagslave.linux.i386
before_script:
  - sudo socat -d -d pty,mode=777,raw,echo=0,link=/dev/tty.modbus.rtu_diagslave_side pty,mode=777,raw,echo=0,link=/dev/tty.modbus.rtu &
  - sudo socat -d -d pty,mode=777,raw,echo=0,link=/dev/tty.modbus.rtu_over_tcp_diagslave_side tcp-listen:5020,reuseaddr &
  - sudo socat -d -d pty,mode=777,raw,echo=0,link=/dev/tty.modbus.ascii_diagslave_side pty,mode=777,raw,echo=0,link=/dev/tty.modbus.ascii &
  - sudo socat -d -d pty,mode=777,raw,echo=0,link=/dev/tty.modbus.ascii_over_tcp_diagslave_side tcp-listen:5021,reuseaddr &
  - sleep 3
  - ~/diagslave.linux.i386 -m rtu /dev/tty.modbus.rtu_diagslave_side &
  - ~/diagslave.linux.i386 -m rtu /dev/tty.modbus.rtu_over_tcp_diagslave_side &
  - ~/diagslave.linux.i386 -m ascii /dev/tty.modbus.ascii_diagslave_side &
  - ~/diagslave.linux.i386 -m ascii /dev/tty.modbus.ascii_over_tcp_diagslave_side &
  - sleep 3
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip
script:
  - go test -v github.com/xft/modbus/test
